//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SalesforceCdcEdiHub.WinForms.Properties;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

	private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

	public static Settings Default {
		get {
			return defaultInstance;
			}
		}

	[global::System.Configuration.UserScopedSettingAttribute()]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Configuration.DefaultSettingValueAttribute("")]
	public string SelectedTab {
		get {
			return ((string)(this["SelectedTab"]));
			}
		set {
			this["SelectedTab"] = value;
			}
		}

	[global::System.Configuration.UserScopedSettingAttribute()]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Configuration.DefaultSettingValueAttribute("test")]
	public string cmbObjects {
		get {
			return ((string)(this["cmbObjects"]));
			}
		set {
			this["cmbObjects"] = value;
			}
		}

	public string cmbField { get; internal set; }
	}
